### ISSUE TITLE
HTML要素生成に関する閉じタグの不足

### ISSUE THREAD

**Issue by Lambda-deep** [ShikemokuMK/tyranoscript#130]
### 概要  
`this.j_image`で生成されるHTMLコードにおいて、`<div>`タグの閉じが適切でないため、不正なHTML構造が生成されます。

---

### 該当コード  

https://github.com/ShikemokuMK/tyranoscript/blob/c763ee2913307fd90f09461c98c2cc1efd2e481b/tyrano/plugins/kag/kag.tag_system.js#L3388

---

### 問題点  
`<div>`タグの閉じ括弧が抜けているため、以下のようにブラウザで生成されます。

```html
<div class="remodal-base">
  <div class="remodal-image" <="" div=""></div>
</div>
```

---

#131 で修正

**Comment by ShikemokuMK** [comment]
対応しました。ありがとうございます。
