### ISSUE TITLE
buttonのroleにautoを追加してほしい。

### ISSUE THREAD

**Issue by nei-toy** [ShikemokuMK/tyranoscript#48]
tyrano.plugin.kag.tag.buttonに、
【autostart】オート開始　を割り当てたrole=autoを追加してもらえると嬉しいです。

case "auto":
    that.kag.ftag.startTag("autostart", {});
    break;

ご検討よろしくお願いします。

**Comment by ShikemokuMK** [comment]
role=auto に対応しました。
長らくタグリファレンスに追加忘れ。
