### ISSUE TITLE
marginr,marginbがあっても文字がそこで折り返されない

### ISSUE THREAD

**Issue by AknEp** [ShikemokuMK/tyranoscript#50]
メッセージレイヤにmarginr、marginbを設定してあっても、そこで折り返されません。
DOMを見てみると、どうやら inner として作っている div の width が本来ありうべきサイズよりも右まで溢れていることを確認しました。

原因は以下の部分です。

https://github.com/ShikemokuMK/tyranoscript/blob/master/tyrano/plugins/kag/kag.tag.js#L1523

こちらでは暫定的に、以下のような形にすることで改善される事を確認していますが、
コントリビュートのポリシーが分からないので、とりあえずPRにはしておりません。

```
        var marginx = 0;
        if (pm.marginr != "0") marginx += parseInt(pm.marginr);
        if (pm.marginl != "0") marginx += parseInt(pm.marginl);
        var marginy = 0;
        if (pm.margint != "0") marginy += parseInt(pm.margint);
        if (pm.marginb != "0") marginy += parseInt(pm.marginb);

        if (pm.marginl != "0")
            new_style_inner["padding-left"] = parseInt(pm.marginl) + "px";
        if (pm.margint != "0")
            new_style_inner["padding-top"] = parseInt(pm.margint) + "px";
        if (pm.marginr != "0" || pm.marginl != "0"){
            new_style_inner["width"] = (parseInt(layer_inner.css("width")) - marginx ) + "px";
        }
        if (pm.marginb != "0" || pm.margint != "0")
            new_style_inner["height"] = (parseInt(layer_inner.css("height")) - marginy ) + "px";
```

また、ここでチェックしている値が `pm` のものですが、この場合、以下のようなコードでおかしくなると思います。

```
[position layer=message0 width=1280 marginr=40]
[position layer=message0 frame=frame.png marginl=40]
```

二回目の呼び出しでは、pm.marginlやmarginrが空なのが原因です。

内部モデルのパラメータに保持して次の呼び出しでも使えるようにするなどすれば改善されるのではないでしょうか。追加機能でお忙しい中と思いますが、ご検討ください。

PRにして欲しい、動く再現コードが欲しい、という事でしたら用意します。

**Comment by ShikemokuMK** [comment]
widthのサイズが、適切に処理されていない事が原因。
お問い合わせも多く、既存のゲームの動作に影響しますのでアナウンスを周知した上で修正をリリース致します。ありがとうございました。
