### ISSUE TITLE
リソースのロードに失敗した時、リトライ出来ず、復帰も出来ない件

### ISSUE THREAD

**Issue by AknEp** [ShikemokuMK/tyranoscript#51]
リソースのロードに失敗すると、エラーが出た後、進行不能になります。
これは現時点では仕様だと思うのですが、これを改善する予定はありまですでしょうか。

ブラウザゲームとして公開していると、プレイヤーが不安定なネットワーク環境下でプレイすることがあります。そういった時のための復帰手段がないのは残念です。

競合エンジンである（と僕は思っています） novelsphere.js などは、この辺りの扱いが丁寧です。
Chromeの開発者機能で不安定なネットワークの挙動をエミュレートできます。

利用させて頂いていて気になった点でした。ご検討ください。

**Comment by ShikemokuMK** [comment]
「不安定なネットワーク環境下でプレイ」という点で
エラーハンドリングの余地は大いにあると感じておりますので、改善を検討いたします。

おそらく「通信不良が原因の進行不能にさせない」というアプローチで
通信回復後のリトライなどを促す感じになるかと存じます。

ご指摘、有難うございます。
