### ISSUE TITLE
&で始まるテキストが期待通り表示されない

### ISSUE THREAD

**Issue by ruu2** [ShikemokuMK/tyranoscript#81]
&で始まるテキストが期待通り表示されません。
たとえば以下のスクリプトはフリーズします。

```
↓「&あああ」と表示させてみます[r]
&あああ[p]
```

以下のスクリプトを走らせてみるに置換されているように見えます。

```
[eval exp="f.a='あ'"]
↓「&f.a」と表示させてみます[r]
&f.a[p]
```

関連：https://github.com/ShikemokuMK/tyranoscript/issues/80

**Comment by ShikemokuMK** [comment]
thanks
