### ISSUE TITLE
iPadのブラウザでembタグの実行時に進行不能になるコードがある

### ISSUE THREAD

**Issue by cat2151** [ShikemokuMK/tyranoscript#83]
## 詳しくは
https://github.com/cat2151/tyranoscript5_for_iPad_browser_test_20210321
にまとめました。

上記のコードを iPad のブラウザ（safari、chrome、Firefoxいずれも）で実行すると進行不能になりますが、
Windows PC では問題なく動作します。

## 原因考察
  - Windows PCで動くのはたまたまで、上記コードが間違っているのでは？
  - それともティラノスクリプトと iOS とでなんらかの相性問題がある？
  - それとも別の原因？

等、考えたのですが、知識不足ゆえ結論は出せませんでした。

##  報告するかどうか？
もし万一相性問題で、このコードがその解決の参考になるなら、
拙速ではあれど報告したほうがよさそうと判断しました。

もしただのコードミス等だった場合ご迷惑をおかけすることになり申し訳ありません。

なにかの参考になれば幸いです。

**Comment by cat2151** [comment]
モバイルであれば、WindowsPCでも再現しました。
WIndows版chromeのデベロッパーツールのモバイルエミュレーターで再現しました。

**Comment by bombastus1541** [comment]
@ShikemokuMK @ogihara88sai 
以下の箇所でclickとtouchstartにイベントハンドラをセットしているのでモバイルでは２回処理が実行されるようです。
ただ、何か理由があってこのコードになっている可能性もあるので一度ご確認いただけますか？
https://github.com/ShikemokuMK/tyranoscript/blob/87e59cc693bf11e23b0c2bb777efaf1584016bb4/tyrano/plugins/kag/kag.tag.js#L3430

**Comment by ogihara88sai** [comment]
問題点のご提示に感謝いたします。**touchstart イベントハンドラを削除し、click イベントハンドラのみをセットする**方向に舵を切りたいと思います。以下、詳細です。

---

#### touchstart が追加されたコミット

> 以下の箇所でclickとtouchstartにイベントハンドラをセットしている
>  j_span.bind("click touchstart", function (e) { 

こちらは、もともと click だけであった部分に、2016年7月10日のコミット「iOSでlinkが効かなくなる対策」によって touchstart が追加された経緯がありました。
https://github.com/ShikemokuMK/tyranoscript/commit/78cd21be5f7cc15703d7a3074c0585ee4e03c52d

#### touchstart が追加された理由

実装理由が記録・記憶に残っておらず推測になりますが、おそらく当時、iOS において「span 要素に対して click が発火しない」ような不具合があり、そのために touchstart イベントハンドラを追加したものと思われます。

#### 問題の発覚が遅れた理由

click と touchstart の両方にイベントハンドラをセットする実装であっても、`[link] のジャンプ先に [cm] が設置してあり、touchstart でジャンプした瞬間にリンクテキストがDOMから削除される`ケースでは click が発火しなくなるため、イベントハンドラが二重に実行されることはなく、正常に動作していました。これが問題の発覚を遅らせる原因となっておりました。

しかし`[link] のジャンプ先に [cm] を設置せずにそのままメッセージウィンドウにテキストを追加していく`ようなスクリプト（これは開発者の想定しない使用方法でした）では、たしかに click と touchstart が両方発火し、イベントハンドラが二重に実行されてしまいます。また、ジャンプ先が別のシナリオファイルでその読み込みが発生する場合などにもイベントハンドラが二重に実行される可能性があるように思います。

#### 対処

2022年現在、iOS / Android ともに click イベントハンドラのみでも動作することが確認できたため、touchstart を削除し click イベントハンドラのみをセットする実装に変更しました。
https://github.com/ogihara88sai/tyranoscript/commit/07db90e75d3f9acdb2114b1b97d82855a48442c7
