### ISSUE TITLE
回想モードから設定画面に行って戻ると一時変数が消える

### ISSUE THREAD

**Issue by bombastus1541** [ShikemokuMK/tyranoscript#95]
https://github.com/ShikemokuMK/tyranoscript/blob/e46b9f516d99f77e7de2a4c5f4c553397359f4ea/tyrano/plugins/kag/kag.menu.js#L1016

上記の箇所でtfをクリアしていますが、これだと回想状態を保持しているtf.flag_replayも消えます。
回想中に設定画面へ行って戻って来るような場合、awakegameからloadGameDataが呼ばれるので、戻った先で回想中ではなくなってしまいます。

**Comment by ogihara88sai** [comment]
`clearTmpVariable()`を実装したコミット (https://github.com/ShikemokuMK/tyranoscript/commit/c7158793a3d3cd502880aab86422ee100ce6e261) における考慮漏れと思われましたので、tf.flag_replay を tf.system.flag_replay に移動する変更を行ないました。(https://github.com/ogihara88sai/tyranoscript/commit/a0089b7490ec8d358ac31c14a4ec50a70c2f7d4c)
